# Generated by Django 4.2.5 on 2023-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('star', models.IntegerField()),
            ],
        ),
    ]
